sudo: false
language: go

go:
  - '1.10.2'
  - '1.10.1'

go_import_path: app.ysitd/proxy

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v -vendor-only

script:
  - go vet -v ./...
  - go test -v ./...